### ISSUE TITLE
primereact-app-realm.json can't import to keycloak

### ISSUE THREAD

**Issue by lewis-ing** [czetsuya/Spring-Keycloak-with-REST-API#1]
this is error info:
![image](https://user-images.githubusercontent.com/5885520/71301786-af5c6000-23de-11ea-94d0-9ab2ea5f07b4.png)

**Comment by czetsuya** [comment]
Hi, it would help if you can share a part of your server log. But a common issue would be an incompatible Keycloak version.

**Comment by lewis-ing** [comment]
this is error log:

![image](https://user-images.githubusercontent.com/5885520/71308049-430b4c00-2432-11ea-8c8d-52fa071ebcf6.png)

**Comment by czetsuya** [comment]
Are you perhaps running Keycloak on Docker? Can you try downloading a new zipped version of Keycloak and try to import it there.

**Comment by lewis-ing** [comment]
No,I download Keycloak 8.0.1 version at windows,do you primereact-app-realm.json file,upload this.

**Comment by czetsuya** [comment]
Hmm. Can you try using version Keycloak server 6.0.1 and see if the same error will occur? I read somewhere that this feature has been removed from 7.0.0.

**Comment by czetsuya** [comment]
I think I figured out the problem it seems like Keycloak team has introduced the notion of feature and uploading the json file has become one of them. Sadly, it is disable by default. To enable realm upload run Keycloak like:

>standalone.bat -Dkeycloak.profile.feature.upload_scripts=enabled

Here's the documentation: https://www.keycloak.org/docs/latest/server_installation/

**Comment by lewis-ing** [comment]
It's ok,using standalone.bat " -Dkeycloak.profile.feature.upload_scripts=enabled" for start cmd,

I run server and front,I tried to add customer info,yet exists error info, please error capture image,

![image](https://user-images.githubusercontent.com/5885520/71318678-04779f00-24cf-11ea-98aa-e218cbad91a4.png)

**Comment by czetsuya** [comment]
That must be due to the Web Origins setting inside your Client. For testing purposes, you can set it to "*". Set the valid redirect URLs to "*" too. But don't forget to change them when you go live. 

What is CORS?
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by lewis-ing** [comment]
yes,I found it, should you setting "bearer-only" at keycloak "springboot-rest-api" for back server.

![image](https://user-images.githubusercontent.com/5885520/71318991-207d3f80-24d3-11ea-9fb9-495edf4a3def.png)

Thanks czetsuya.
